GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${username};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${username};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${nr_username};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${nr_username};