integration_name: com.newrelic.redis

instances:
  - name: redis-metrics
    command: metrics
    arguments:
      hostname: localhost
      port: 6379
      keys: '{"0":["<KEY_1>"],"1":["<KEY_2>"]}'
    labels:
      - environment: production

  - name: redis-inventory
    command: inventory
    arguments:
      hostname: localhost
      port: 6379
    labels:
      - environment: production